In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import pickle

df = pd.read_csv('Iris.csv')

x = df.iloc[:, 1:-1]
y = df.iloc[:, -1]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 1)

model = LogisticRegression()
model.fit(x_train, y_train)

pickle.dump(model, open('irisModel.pkl', 'wb'))

model = pickle.load(open('irisModel.pkl', 'rb'))
print(model.predict([[5.3, 2.3, 7.4, 2.1], ]))

['Iris-virginica']


In [2]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model.predict(x_test)
cm = confusion_matrix(y_pred, y_test)
print(cm)

[[5 0 0]
 [0 6 0]
 [0 0 4]]


In [3]:
acc = accuracy_score(y_pred, y_test)
acc

1.0

In [4]:
df.shape

(150, 6)